### ISSUE TITLE
About Evaluation settings

### ISSUE THREAD

**Issue by LittleFlyingSheep** [audio-captioning/dcase-2020-baseline#10]
According your 'Readme', if I want evaluate the model I have trained, I should change the settings of 'dirs_and_files.yaml', 'model_baseline.yaml' and 'method_baseline.yaml'. 

Then, I find the settings in 'dirs_and_files.yaml' as follows:
![image](https://user-images.githubusercontent.com/38974045/117530091-d801eb80-b00d-11eb-8cd0-f452912d45fa.png)
Is it right? In fact, I feel puzzled with the 'checkpoint_model_name'. What should it be in this work?

In 'model_baseline.yaml', I change the 'use_pre_trained_model: Yes'. However, in 'method_baseline.yaml', I did not find the settings for evaluation. It looks like a whole training yaml file. What should I do when evaluating with the 'method_baseline.yaml'?

**Comment by LittleFlyingSheep** [comment]
All right. I know the 'checkpoint_model_name' is the save name for my net.

**Comment by dr-costas** [comment]
I’m glad that you found out!
