### ISSUE TITLE
Question regarding pretrained weights

### ISSUE THREAD

**Issue by gretatuckute** [audio-captioning/dcase-2020-baseline#12]
Hi! Thank you for this great repository. I have a quick question regarding the pretrained weights for the baseline system (https://zenodo.org/record/3697687#.YKJp7-spCuo). I do not see this mentioned explicitly (sorry if I missed it), but were these weights obtained from training on the training split of Clotho v1 or v2? The results [here](http://dcase.community/challenge2021/task-automatic-audio-captioning#baseline-system) are reported as v1? 

thanks so much!
Greta

**Comment by dr-costas** [comment]
Hi Greta, 

Thank you for the message! Indeed, the current results are for Clotho v1. I hope that during this week we will be releasing the results for v2. 

I tried to explicitly mention this at the [baseline for DCASE](http://dcase.community/challenge2021/task-automatic-audio-captioning#results-for-the-development-dataset)

> The results of the baseline system for the development dataset are (**with Clotho V1**, will be updated for Clotho v2):

But I totally understand that it is not always that easy to find info in big walls of text. I had similar experience too many times myself as well :D 

Let me know if the above is OK for you or something more is needed. :)

**Comment by gretatuckute** [comment]
Thanks so much for the quick reply, appreciate it! Great, so results are from v1, which also means that the pretrained weights are trained on the development split of Clotho v1? Which consists of 2893 audio clips with 14465 captions, right?

**Comment by dr-costas** [comment]
Yes.

**Comment by gretatuckute** [comment]
Beautiful, thank you!
