### ISSUE TITLE
Reminder about JAVA jdk version issue in doing evaluation

### ISSUE THREAD

**Issue by keepcreative** [audio-captioning/dcase-2020-baseline#14]
i wander if any one faced these errors  like me when doing evaluation:
`subprocess.CalledProcessError: Command '['/usr/java/jdk-16.0.2/bin/java', '-jar', '-Xmx8G', 'spice-1.0.jar', '/data1/coco-caption/pycocoevalcap/spice/tmp/tmpe6faasnb', '-cache', '/data1/coco-caption/pycocoevalcap/spice/cache/1634609092.4812038', '-out', '/data1/coco-caption/pycocoevalcap/spice/tmp/tmpv2_jep2k', '-subset', '-silent']' returned non-zero exit status 1.`
or
`File "D:\dcase-2021-baseline-master\coco_caption\pycocoevalcap\tokenizer\ptbtokenizer.py", line 58, in tokenize
    stdout=subprocess.PIPE)
  File "C:\Users\admin\miniconda3\envs\dcase-2021-baseline-master\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\admin\miniconda3\envs\dcase-2021-baseline-master\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2]`

After installing 'Java SE Development Kit 8u361' instead of higher version, the problem solved.

**Comment by Schwartz-Zha** [comment]
How long does it take to compute the spice in each iteration? I see all my CPU cores are working at 100%, but I don't see a result for a long period. I want to make sure that they are not in an infinite loop.
