### ISSUE TITLE
Reproducibility of results

### ISSUE THREAD

**Issue by NadineKroher** [audio-captioning/dcase-2020-baseline#3]
First of all, thanks for putting the code together!

I have an issue when trying to reproduce the results reported on the DCASE task website. 

Running main.py with settings

workflow:
  dataset_creation: Yes
  dnn_training: No
  dnn_evaluation: Yes

using the pre-trained model (https://doi.org/10.5281/zenodo.3697687), I get results that differ from the ones reported in 

http://dcase.community/challenge2020/task-automatic-audio-captioning#results-for-the-development-dataset 

I am currently getting the following:
 bleu_1 :  0.3893
 bleu_2 :  0.1353
 bleu_3 :  0.0542
 bleu_4 :  0.0150
 meteor :  0.0839
 rouge_l:  0.2622
 cider  :  0.0737
 spice  :  0.0332
 spider :  0.0535

Should I get the same results? Is there anything I am missing?

**Comment by dr-costas** [comment]
Hi, 

Thank you for the issue. You should get the same results as the ones reported at the website. 

Let me check it and I will let you know.

**Comment by NadineKroher** [comment]
Thanks. 

I made one minor modification to be able to load the model on CPU (in model.py):

`        if get_device(force_cpu=False)[0] == 'cpu': `
`            model.load_state_dict(pt_load(Path(`
`                settings_io['root_dirs']['outputs'],`
`                settings_io['model']['model_dir'],`
`               settings_io['model']['pre_trained_model_name'],`
`          ), map_location=device('cpu')))`
`        else:`
`            model.load_state_dict(pt_load(Path(`
`                settings_io['root_dirs']['outputs'],`
`                settings_io['model']['model_dir'],`
`                settings_io['model']['pre_trained_model_name']`
`            )))`

**Comment by dr-costas** [comment]
Update:

I just run the code again, and I'm getting the results reported on the webpage. 

The only explanation is that I accidentally zipped and uploaded wrong model. I will check that I will come back.

**Comment by dr-costas** [comment]
Update: 

Nope! I get exactly the same results as the ones reported on the webpage. Just checked. 

Can you please check it on your machine but on a GPU? MIght be something weird type conversion error (e.g. from float32 to float64).

**Comment by dr-costas** [comment]
Oh! good catch for the memory map of the weights. I will fix it on the code. Thank you for bring that up!

**Comment by NadineKroher** [comment]
thanks! a colleague will run the code on GPU and i will let you know once we get results...

**Comment by dr-costas** [comment]
I will test it on CPU as well.

**Comment by dr-costas** [comment]
Again, on CPU I get the same results as the ones reported on the website. 

Please check that you have correct file name at the `settings/dirs_and_files.yaml` file.

**Comment by NadineKroher** [comment]
ok, I checked the paths, tried a fresh install of all components just in case, but I still get the same results. 

I will attach the caption_baseline.txt file - maybe we can in this way find out if the problem is on the data creation or evaluation side of things...

[captions_baseline.txt](https://github.com/audio-captioning/dcase-2020-baseline/files/4320161/captions_baseline.txt)

**Comment by dr-costas** [comment]
Thank you for the info. I will have a look on it and let you know.

**Comment by dr-costas** [comment]
Sorry for the delay. We are running tests to find what is happening with this issue.

**Comment by dr-costas** [comment]
Hi again, 

We run some tests (and we are still running some more) and we found that there are differences at the values of the features, if you use different version of `numpy` than the one used. 

Specifically, there are differences in the values of the features if you use version 1.17 and version 1.18. The differences have the following statistics for the two splits of Clotho: 

**Development split**
Mean: 4.160630123806186e-05
Max: 0.0010153684997931123
Min: 2.0349598344182596e-05
Variance: 8.895943981457322e-10

**Evaluation split**
Mean: 4.031339631183073e-05
Max: 0.0005783048691228032
Min: 1.9362085367902182e-05
Variance: 3.498585865457926e-10

Please let us know what version of numpy as you using and getting different results. 

----

Kudos to @lippings for calculating these statistics for the different versions of numpy, using the code of the DCASE 2020 audio captioning baseline system.

**Comment by NadineKroher** [comment]
Hi!

Thanks for all that work! I used venv to create a new environment and then the requirements_pip.txt file to install dependencies. 

pip freeze gives me:
audioread==2.1.8
cffi==1.14.0
cycler==0.10.0
decorator==4.4.2
imageio==2.8.0
joblib==0.14.1
kiwisolver==1.1.0
librosa==0.7.1
llvmlite==0.31.0
loguru==0.3.2
matplotlib==3.2.0
networkx==2.4
numba==0.48.0
numpy==1.17.4
Pillow==7.0.0
pycparser==2.20
pyparsing==2.4.6
python-dateutil==2.8.1
PyWavelets==1.1.1
PyYAML==5.1.2
resampy==0.2.2
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.4.1
six==1.14.0
SoundFile==0.10.3.post1
torch==1.3.1

I hope this helps...

**Comment by NadineKroher** [comment]
btw. if this is indeed the issue, then the difference in metrics it causes is very interesting!

**Comment by dr-costas** [comment]
It seems that there is another bug, related to the parsing and ordering of the validation file names. Therefore, there are new values for the baseline. 

I just have pushed a change and the new values for the metrics should be: 

Bleu1: 0.39
Bleu2: 0.14
Bleu3: 0.05
Bleu4: 0.01
METEOR: 0.08
CIDEr: 0.07
SPICE: 0.03
SPIDEr: 0.05

Can you please let me know if you are getting the same results?

**Comment by NadineKroher** [comment]
Yes - this is exactly what I am getting! Thanks guys!

**Comment by dr-costas** [comment]
Thank you too for spotting this and helping us to solve it.

**Comment by dr-costas** [comment]
I'm closing this issue. Please feel free to make a new one if something else happens.
