### ISSUE TITLE
For test set.

### ISSUE THREAD

**Issue by WangHelin1997** [audio-captioning/dcase-2020-baseline#5]
Hi. According to http://dcase.community/challenge2020/task-automatic-audio-captioning#submission, participants are required to submit the output of their audio captioning method for each of the 1043 files in the evaluation split.

Could you please **release the codes for the submission** of DCASE2020 Task6? 
Thanks a lot.

**Comment by dr-costas** [comment]
Hi @WangHelin1997 

and thank you for your message. 

As the text says: 

> participants are required to submit the output of their audio captioning method for each of the 1043 files in the evaluation split **(which will be available according to DCASE Challenge schedule)**.

The code and the test set will be released close to the date of the test set release, according to the schedule of the DCASE challenge. 

I hope that the above help! 

Cheers!

**Comment by WangHelin1997** [comment]
Thanks!
Best wishes.

**Comment by dr-costas** [comment]
Because your question is really relevant to the code until the release of the test set, I will leave this issue open so other people can find it easily.

**Comment by dr-costas** [comment]
Dear @WangHelin1997 

Now you can find at the DCASE website all the information about the evaluation of methods for audio captioning (Task 6) and we have also updated the baseline system code with the functionality for the evaluation process. 

I wish you best of luck with your submission!

**Comment by WangHelin1997** [comment]
Dear @dr-costas 

Thanks for your updation.
I still wonder how I can train on both the development and evaluation set according to the task rules. Is it OK that I simpily set 'dnn_training: Yes' ?

**Comment by dr-costas** [comment]
Dear @WangHelin1997 

Sorry for the delayed reply. 

Setting the flag will not suffice for using al the data. But, if you already have your method ready and you just want to train it with all data, you can mix the data in the same folder (i.e. put all data in the same folder) and use the existing set up. 

Let me know if you have any more questions! 

I wish best of luck with your method!
