### ISSUE TITLE
Potential SPICE calculation issues

### ISSUE THREAD

**Issue by ghost** [audio-captioning/dcase-2020-baseline#6]
When running Evaluation, this error could happen:
`subprocess.calledprocesserror: command '[subprocess.calledprocesserror'java', '-jar', '-xmx8g', 'spice-1.0.jar', <some more commands> -subset -silent returned non-zero exit status 1.`

**Comment by ghost** [comment]
This is how I work around the issue:

1) Make sure Stanford CoreNLP is installed: 
```
cd coco_caption/
./get_stanford_models.sh
```

2)If the error still persists:
-Navigate to spice folder: `cd pycocoevalcap/spice/`
-In `spice.py`, line 68-73:
```
spice_cmd = ['java', '-jar', '-Xmx2048m', SPICE_JAR, in_file.name,  #<-Try with lower memory instead of Xmx8G
# '-cache', cache_dir, <- Not using cache
'-out', out_file.name,
'-subset',
 '-silent'
]
```

**Comment by Schwartz-Zha** [comment]
How long does it take to compute this stage, specifically, the SPICE score in each evaluation? All my CPU cores are running at 100% for a long while, not sure if this is a bug or normal behaviour.
